"""empty message

Revision ID: 0f0566fdb187
Revises: c79c7c1f505f
Create Date: 2024-11-28 20:59:52.569700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0566fdb187'
down_revision: Union[str, None] = 'c79c7c1f505f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'cart', ['product_id'])
    op.add_column('order', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'quantity')
    op.drop_constraint(None, 'cart', type_='unique')
    op.drop_column('cart', 'quantity')
    # ### end Alembic commands ###
