"""empty message

Revision ID: 32be0099cacb
Revises: e8fa8ede44dc
Create Date: 2024-11-26 22:02:21.256200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32be0099cacb'
down_revision: Union[str, None] = 'e8fa8ede44dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'name')
    # ### end Alembic commands ###
