"""empty message

Revision ID: 44e600c753aa
Revises: 1179764724c3
Create Date: 2024-11-22 02:51:42.890876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44e600c753aa'
down_revision: Union[str, None] = '1179764724c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', name='userstatus'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('active', 'inactive', name='userstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
