"""empty message

Revision ID: 5330599574d0
Revises: 332991ba8d82
Create Date: 2024-11-29 11:50:48.066140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5330599574d0'
down_revision: Union[str, None] = '332991ba8d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_product_id_key', 'cart', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cart_product_id_key', 'cart', ['product_id'])
    # ### end Alembic commands ###
