"""empty message

Revision ID: e2e82dbfe759
Revises: 0f0566fdb187
Create Date: 2024-11-28 21:13:21.108663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2e82dbfe759'
down_revision: Union[str, None] = '0f0566fdb187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_longitude_latitude', 'address', ['longitude', 'latitude'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_longitude_latitude', 'address', type_='unique')
    # ### end Alembic commands ###
